services:
  postgres:
    image: postgres:16
    container_name: live_attendance_system
    restart: always
    environment:
      POSTGRES_USER: live_user
      POSTGRES_PASSWORD: supersecret123
      POSTGRES_DB: attendance_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
